// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
)

// Injectors from wire.go:

func InitApplication(ctx context.Context) (*App, func(), error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := ProvidePostgres(config)
	if err != nil {
		return nil, nil, err
	}
	userRepository, err := ProvideUserRepository(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userUsecase := ProvideUserUsecase(userRepository)
	authUsecase := ProvideAuthUsecase(userUsecase)
	authDelivery := ProvideAuthDelivery(authUsecase)
	talentRepository, err := ProvideTalentRepository(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	talentUsecase := ProvideTalentUsecase(talentRepository)
	talentDelivery := ProvideTalentDelivery(talentUsecase)
	userDelivery := ProvideUserDelivery(userUsecase)
	handler := ProvideHttpHandler(authDelivery, talentDelivery, userDelivery)
	server := ProvideRestService(handler)
	app := &App{
		server: server,
	}
	return app, func() {
		cleanup()
	}, nil
}
